apiVersion: apps/v1
kind: Deployment
metadata:
  # The name of the deployment, using the fullname template
  name: {{ include "httpbin.fullname" . }}
  labels:
    # Standard labels for the deployment
    {{- include "httpbin.labels" . | nindent 4 }}
spec:
  # Number of desired pods
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      # Selector labels for the deployment
      {{- include "httpbin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        # Labels for the pod template
        {{- include "httpbin.selectorLabels" . | nindent 8 }}
      annotations:
        # Annotations for the pod template
        {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      securityContext:
        # Pod-level security context
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            # Container-level security context
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          command: ["gunicorn", "-b", ":8080", "httpbin:app", "-k", "gevent"]
          resources:
            # Resource requests and limits for the container
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            # Liveness probe configuration
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            # Readiness probe configuration
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: tmpfs
              mountPath: /tmp
      {{- with .Values.nodeSelector }}
      nodeSelector:
        # Node selector for pod assignment
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        # Affinity rules for pod scheduling
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        # Tolerations for pod scheduling
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        # Topology spread constraints for pod distribution
        {{- toYaml . | nindent 8 }}
      {{- end }}

      # Fix according  https://docs.gunicorn.org/en/latest/faq.html#blocking-os-fchmod
      volumes:
        - name: tmpfs
          emptyDir:
            medium: Memory