apiVersion: v1
kind: Service
metadata:
  # The name of the service, using the fullname template
  name: {{ include "httpbin.fullname" . }}
  labels:
    # Standard labels for the service
    {{- include "httpbin.labels" . | nindent 4 }}
spec:
  # The type of the service
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      # Name of the port
      name: http
  selector:
    # Selector labels for the service
    {{- include "httpbin.selectorLabels" . | nindent 4 }}