apiVersion: v2
name: operator
description: A Helm chart for the Operator application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - golang
  - web
  - operator
home: https://github.com/your-username/GamesOperator
sources:
  - https://github.com/your-username/GamesOperator
maintainers:
  - name: Your Name
    email: your.email@example.com 